export const actionTypes = {
  TOGGLE_ERROR: 'TOGGLE_ERROR',
  FETCH_DATA_START: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  SET_REPO_COUNT: 'SET_REPO_COUNT',
  FETCH_COMMITS_START : 'FETCH_COMMITS_START',
  FETCH_COMMITS_SUCCESS : 'FETCH_COMMITS_SUCCESS',
  SET_LAST_COMMITER : 'SET_LAST_COMMITER',
  TOGGLE_ASCENDING_ORDERING : 'TOGGLE_ASCENDING_ORDERING',
  TOGGLE_DESCENDING_ORDERING : 'TOGGLE_DESCENDING_ORDERING'
};
