export const actionTypes = {
  TOGGLE_ERROR: 'TOGGLE_ERROR',
  FETCH_DATA_START: 'FETCH_DATA',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
  SET_REPO_COUNT: 'SET_REPO_COUNT',
  SET_AVATAR_IMG: 'SET_AVATAR_IMG',
};
